version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: prova-facil-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prova_facil
    volumes:
      # Persiste dados do banco
      - postgres_data:/var/lib/postgresql/data
      # Inicialização (migrations, inserts, policies, triggers)
      - ./db/migrations:/docker-entrypoint-initdb.d/migrations:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prova-facil-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: prova-facil-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      # Persiste cache do Redis (AOF)
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - prova-facil-network

  # Redis Commander (Interface Web para Redis) - Opcional
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: prova-facil-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - prova-facil-network
    profiles:
      - tools

  # Adminer (Interface Web para PostgreSQL) - Opcional
  adminer:
    image: adminer:latest
    container_name: prova-facil-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - prova-facil-network
    profiles:
      - tools

# Volumes persistentes
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

# Network
networks:
  prova-facil-network:
    driver: bridge
