version: "3.8"

services:
    db:
        image: postgres:15-alpine
        container_name: prova_facil_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "54322:5432" # matches .env DATABASE URL
        volumes:
            - ./supabase/db_data:/var/lib/postgresql/data
            - ./supabase/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost -p 5432"]
            interval: 10s
            timeout: 5s
            retries: 5

    pgadmin:
        image: dpage/pgadmin4:7
        container_name: prova_facil_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@local
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "8080:80"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        depends_on:
            - db
