// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://jjysfdhfnfuvyudybumf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqeXNmZGhmbmZ1dnl1ZHlidW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMTM1ODEsImV4cCI6MjA3NDY4OTU4MX0._Xws43qZjxFilBbHm5PLF4hkOi9PbdhvD3iOMe64xN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    },
});
